services:
  - type: web
    name: netflix-cookie-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install chromium --with-deps
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true
